name: Automate Selenium Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Selenium Hub
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.192.168.0.113 }}
        username: ${{ secrets.OB-7 }}
        password: ${{ secrets.OB_2020 }}
        port: 22 # Default SSH port
        script: |
          java -jar "C:\\wamp64\\www\\selenium-server-standalone-3.141.59.jar" -role hub

    - name: Start WebDriver Node
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: 22 # Default SSH port
        script: |
          cd C:\\wamp64\\www\\photoadking_editor_automation
          java -Dwebdriver.chrome.driver="C:\\wamp64\\www\\chromedriver.exe" -jar "C:\\wamp64\\www\\selenium-server-standalone-3.141.59.jar" -role webdriver -hub http://192.168.0.113:4444/register -port 4546

    - name: Run Test Suite
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: 22 # Default SSH port
        script: |
          cd C:\\wamp64\\www\\photoadking_editor_automation
          mvn clean test -Dfilename=Suite.xml
